
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'pt' | 'en' | 'es' | 'fr' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pt: {
    'nav.dashboard': 'Dashboard',
    'nav.video': 'Gerar Vídeo',
    'nav.image': 'Gerar Imagem',
    'nav.thumbnail': 'Criar Thumbnail',
    'nav.gallery': 'Galeria IA',
    'nav.history': 'Histórico',
    'nav.plans': 'Planos',
    'nav.admin': 'Painel Admin',
    'nav.logout': 'Sair',
    'credits.remaining': 'Créditos Restantes',
    'credits.upgrade': 'Upgrade',
    'credits.unlimited': 'ilimitado',
    'dashboard.hello': 'Olá',
    'dashboard.subtitle': 'O seu estúdio de criação com Inteligência Artificial.',
    'dashboard.new_project': '+ Novo Projeto',
    'dashboard.credits': 'Créditos',
    'dashboard.renews': 'Renova em 30 dias',
    'dashboard.plan': 'Plano Atual',
    'dashboard.upgrade_link': 'Fazer Upgrade',
    'dashboard.status': 'Status da Rede',
    'dashboard.start': 'Comece a Criar',
    'card.video.title': 'Vídeo Studio',
    'card.video.desc': 'Geração de vídeos longos com narração.',
    'card.image.title': 'Image Lab',
    'card.image.desc': 'Crie assets visuais e arte em 4K.',
    'card.thumb.title': 'Thumbnail Maker',
    'card.thumb.desc': 'Capas virais com tipografia otimizada.',
    'common.loading': 'Carregando...',
    'theme.title': 'Tema',
    'theme.cosmic': 'Cosmic (Padrão)',
    'theme.aurora': 'Aurora (Tech)',
    'theme.inferno': 'Inferno (Criativo)',
    // New Generative Pages
    'gen.video.title': 'Novo Vídeo IA',
    'gen.video.subtitle': 'Escolha o modelo de IA, configure a voz e gere vídeos cinematográficos.',
    'gen.model': 'Motor de Inteligência Artificial',
    'gen.prompt': 'Descrição (Prompt)',
    'gen.duration': 'Duração',
    'gen.aspect': 'Proporção (Tamanho)',
    'gen.style': 'Estilo Visual',
    'gen.lang': 'Idioma',
    'gen.captions': 'Legendas',
    'gen.seo': 'SEO Master (Google/YT)',
    'gen.voice': 'Voz da Narração',
    'gen.submit': 'Iniciar Renderização',
    'gen.loading': 'Gerando obra prima...',
    'gen.audio.title': 'Áudio e Atmosfera',
    'gen.audio.music': 'Trilha Sonora (IA)',
    'gen.audio.sfx': 'Efeitos Sonoros (SFX)',
    'gen.image.title': 'Estúdio de Imagem',
    'gen.image.subtitle': 'Transforme texto em arte visual 4K ultra-realista.',
    'gen.thumb.title': 'Thumbnail Maker ⚡',
    'gen.thumb.subtitle': 'Crie capas virais para YouTube com IA e tipografia otimizada.',
    'gen.thumb.bg': 'Cenário / Imagem de Fundo',
    'gen.thumb.text1': 'Texto Principal (Chamativo)',
    'gen.thumb.text2': 'Texto Secundário (Opcional)',
    'history.title': 'Biblioteca de Criações',
    'history.subtitle': 'Gerencie, visualize e baixe seus assets gerados.',
    'history.retention': 'Arquivos armazenados por 90 dias.',
    'history.empty': 'Nenhum conteúdo gerado ainda.',
    'pricing.title': 'Planos & Preços',
    'pricing.subtitle': 'Escolha o nível de poder computacional que você precisa.',
    'pricing.start': 'Começar Agora',
    'pricing.current': 'Seu Plano Atual',
    'login.title': 'Acesse o futuro',
    'login.subtitle': 'Acesse o futuro da criação de conteúdo.',
    'login.email': 'Email',
    'login.pass': 'Senha',
    'login.name': 'Nome',
    'login.submit_in': 'Entrar na Plataforma',
    'login.submit_up': 'Criar Conta Gratuita',
    'login.toggle_in': 'Já tem conta? Faça login',
    'login.toggle_up': 'Não tem conta? Crie agora',
    'error.credits': 'Créditos insuficientes.',
    'error.prompt': 'Por favor, descreva o conteúdo.',
    // Profile
    'profile.title': 'Configurações de Perfil',
    'profile.subtitle': 'Gerencie suas informações pessoais e aparência.',
    'profile.name': 'Nome de Exibição',
    'profile.email': 'Email (Não editável)',
    'profile.avatar': 'URL do Avatar',
    'profile.save': 'Salvar Alterações',
    'profile.saving': 'Salvando...',
    'profile.success': 'Perfil atualizado com sucesso!',
  },
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.video': 'Generate Video',
    'nav.image': 'Generate Image',
    'nav.thumbnail': 'Create Thumbnail',
    'nav.gallery': 'AI Gallery',
    'nav.history': 'History',
    'nav.plans': 'Pricing',
    'nav.admin': 'Admin Panel',
    'nav.logout': 'Logout',
    'credits.remaining': 'Credits Remaining',
    'credits.upgrade': 'Upgrade',
    'credits.unlimited': 'unlimited',
    'dashboard.hello': 'Hello',
    'dashboard.subtitle': 'Your AI-powered content creation studio.',
    'dashboard.new_project': '+ New Project',
    'dashboard.credits': 'Credits',
    'dashboard.renews': 'Renews in 30 days',
    'dashboard.plan': 'Current Plan',
    'dashboard.upgrade_link': 'Upgrade Now',
    'dashboard.status': 'Network Status',
    'dashboard.start': 'Start Creating',
    'card.video.title': 'Video Studio',
    'card.video.desc': 'Generate long-form videos with narration.',
    'card.image.title': 'Image Lab',
    'card.image.desc': 'Create visual assets and 4K art.',
    'card.thumb.title': 'Thumbnail Maker',
    'card.thumb.desc': 'Viral covers with optimized typography.',
    'common.loading': 'Loading...',
    'theme.title': 'Theme',
    'theme.cosmic': 'Cosmic (Default)',
    'theme.aurora': 'Aurora (Tech)',
    'theme.inferno': 'Inferno (Creative)',
    // New Generative Pages
    'gen.video.title': 'New AI Video',
    'gen.video.subtitle': 'Choose AI model, configure voice, and generate cinematic videos.',
    'gen.model': 'Artificial Intelligence Engine',
    'gen.prompt': 'Description (Prompt)',
    'gen.duration': 'Duration',
    'gen.aspect': 'Aspect Ratio',
    'gen.style': 'Visual Style',
    'gen.lang': 'Language',
    'gen.captions': 'Captions',
    'gen.seo': 'SEO Master (Google/YT)',
    'gen.voice': 'Narration Voice',
    'gen.submit': 'Start Rendering',
    'gen.loading': 'Generating masterpiece...',
    'gen.audio.title': 'Audio & Atmosphere',
    'gen.audio.music': 'Soundtrack (AI)',
    'gen.audio.sfx': 'Sound Effects (SFX)',
    'gen.image.title': 'Image Studio',
    'gen.image.subtitle': 'Transform text into ultra-realistic 4K visual art.',
    'gen.thumb.title': 'Thumbnail Maker ⚡',
    'gen.thumb.subtitle': 'Create viral YouTube covers with AI and optimized typography.',
    'gen.thumb.bg': 'Scenery / Background Image',
    'gen.thumb.text1': 'Main Text (Catchy)',
    'gen.thumb.text2': 'Secondary Text (Optional)',
    'history.title': 'Creation Library',
    'history.subtitle': 'Manage, view, and download your generated assets.',
    'history.retention': 'Files stored for 90 days.',
    'history.empty': 'No content generated yet.',
    'pricing.title': 'Plans & Pricing',
    'pricing.subtitle': 'Choose the level of computing power you need.',
    'pricing.start': 'Get Started',
    'pricing.current': 'Your Current Plan',
    'login.title': 'Access the future',
    'login.subtitle': 'Access the future of content creation.',
    'login.email': 'Email',
    'login.pass': 'Password',
    'login.name': 'Name',
    'login.submit_in': 'Enter Platform',
    'login.submit_up': 'Create Free Account',
    'login.toggle_in': 'Already have an account? Login',
    'login.toggle_up': 'No account? Create now',
    'error.credits': 'Insufficient credits.',
    'error.prompt': 'Please describe the content.',
    // Profile
    'profile.title': 'Profile Settings',
    'profile.subtitle': 'Manage your personal information and appearance.',
    'profile.name': 'Display Name',
    'profile.email': 'Email (Read-only)',
    'profile.avatar': 'Avatar URL',
    'profile.save': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.success': 'Profile updated successfully!',
  },
  es: {
    'nav.dashboard': 'Panel',
    'nav.video': 'Generar Video',
    'nav.image': 'Generar Imagen',
    'nav.thumbnail': 'Crear Miniatura',
    'nav.gallery': 'Galería IA',
    'nav.history': 'Historial',
    'nav.plans': 'Precios',
    'nav.admin': 'Panel Admin',
    'nav.logout': 'Cerrar Sesión',
    'credits.remaining': 'Créditos Restantes',
    'credits.upgrade': 'Mejorar',
    'credits.unlimited': 'ilimitado',
    'dashboard.hello': 'Hola',
    'dashboard.subtitle': 'Tu estudio de creación de contenido con IA.',
    'dashboard.new_project': '+ Nuevo Proyecto',
    'dashboard.credits': 'Créditos',
    'dashboard.renews': 'Renueva en 30 días',
    'dashboard.plan': 'Plan Actual',
    'dashboard.upgrade_link': 'Mejorar Plan',
    'dashboard.status': 'Estado de Red',
    'dashboard.start': 'Empieza a Crear',
    'card.video.title': 'Video Studio',
    'card.video.desc': 'Generación de videos largos con narración.',
    'card.image.title': 'Image Lab',
    'card.image.desc': 'Crea activos visuales y arte en 4K.',
    'card.thumb.title': 'Thumbnail Maker',
    'card.thumb.desc': 'Portadas virales con tipografía optimizada.',
    'common.loading': 'Cargando...',
    'theme.title': 'Tema',
    'theme.cosmic': 'Cósmico (Predet.)',
    'theme.aurora': 'Aurora (Tech)',
    'theme.inferno': 'Inferno (Creativo)',
    // New Generative Pages
    'gen.video.title': 'Nuevo Video IA',
    'gen.video.subtitle': 'Elige modelo IA, configura voz y genera videos cinematográficos.',
    'gen.model': 'Motor de Inteligencia Artificial',
    'gen.prompt': 'Descripción (Prompt)',
    'gen.duration': 'Duración',
    'gen.aspect': 'Proporción (Tamaño)',
    'gen.style': 'Estilo Visual',
    'gen.lang': 'Idioma',
    'gen.captions': 'Subtítulos',
    'gen.seo': 'SEO Master (Google/YT)',
    'gen.voice': 'Voz de Narración',
    'gen.submit': 'Iniciar Renderizado',
    'gen.loading': 'Generando obra maestra...',
    'gen.audio.title': 'Audio y Atmósfera',
    'gen.audio.music': 'Banda Sonora (IA)',
    'gen.audio.sfx': 'Efectos Sonoros (SFX)',
    'gen.image.title': 'Estudio de Imagen',
    'gen.image.subtitle': 'Transforma texto en arte visual 4K ultra-realista.',
    'gen.thumb.title': 'Creador de Miniaturas ⚡',
    'gen.thumb.subtitle': 'Crea portadas virales para YouTube con IA.',
    'gen.thumb.bg': 'Escenario / Fondo',
    'gen.thumb.text1': 'Texto Principal',
    'gen.thumb.text2': 'Texto Secundario',
    'history.title': 'Biblioteca de Creaciones',
    'history.subtitle': 'Gestiona, visualiza y descarga tus activos.',
    'history.retention': 'Archivos guardados por 90 días.',
    'history.empty': 'Aún no hay contenido generado.',
    'pricing.title': 'Planes y Precios',
    'pricing.subtitle': 'Elige el nivel de potencia computacional que necesitas.',
    'pricing.start': 'Empezar Ahora',
    'pricing.current': 'Tu Plan Actual',
    'login.title': 'Accede al futuro',
    'login.subtitle': 'Accede al futuro de la creación de contenido.',
    'login.email': 'Correo',
    'login.pass': 'Contraseña',
    'login.name': 'Nombre',
    'login.submit_in': 'Entrar a la Plataforma',
    'login.submit_up': 'Crear Cuenta Gratis',
    'login.toggle_in': '¿Ya tienes cuenta? Inicia sesión',
    'login.toggle_up': '¿No tienes cuenta? Crea una',
    'error.credits': 'Créditos insuficientes.',
    'error.prompt': 'Por favor describe el contenido.',
    // Profile
    'profile.title': 'Ajustes de Perfil',
    'profile.subtitle': 'Gestiona tu información personal y apariencia.',
    'profile.name': 'Nombre para Mostrar',
    'profile.email': 'Correo (No editable)',
    'profile.avatar': 'URL del Avatar',
    'profile.save': 'Guardar Cambios',
    'profile.saving': 'Guardando...',
    'profile.success': '¡Perfil actualizado con éxito!',
  },
  fr: {
    'nav.dashboard': 'Tableau de bord',
    'nav.video': 'Générer Vidéo',
    'nav.image': 'Générer Image',
    'nav.thumbnail': 'Créer Miniature',
    'nav.gallery': 'Galerie IA',
    'nav.history': 'Historique',
    'nav.plans': 'Tarifs',
    'nav.admin': 'Admin',
    'nav.logout': 'Déconnexion',
    'credits.remaining': 'Crédits Restants',
    'credits.upgrade': 'Améliorer',
    'credits.unlimited': 'illimité',
    'dashboard.hello': 'Bonjour',
    'dashboard.subtitle': 'Votre studio de création de contenu par IA.',
    'dashboard.new_project': '+ Nouveau Projet',
    'dashboard.credits': 'Crédits',
    'dashboard.renews': 'Renouvellement dans 30j',
    'dashboard.plan': 'Plan Actuel',
    'dashboard.upgrade_link': 'Mettre à niveau',
    'dashboard.status': 'État du Réseau',
    'dashboard.start': 'Commencer à Créer',
    'card.video.title': 'Video Studio',
    'card.video.desc': 'Vidéos longues avec narration.',
    'card.image.title': 'Image Lab',
    'card.image.desc': 'Créez des visuels et de l\'art 4K.',
    'card.thumb.title': 'Thumbnail Maker',
    'card.thumb.desc': 'Couvertures virales avec typographie.',
    'common.loading': 'Chargement...',
    'theme.title': 'Thème',
    'theme.cosmique': 'Cosmique (Défaut)',
    'theme.aurora': 'Aurore (Tech)',
    'theme.inferno': 'Inferno (Créatif)',
    // New Generative Pages
    'gen.video.title': 'Nouvelle Vidéo IA',
    'gen.video.subtitle': 'Choisissez le modèle IA, la voix et générez des vidéos cinématographiques.',
    'gen.model': 'Moteur d\'Intelligence Artificielle',
    'gen.prompt': 'Description (Prompt)',
    'gen.duration': 'Durée',
    'gen.aspect': 'Format (Taille)',
    'gen.style': 'Style Visuel',
    'gen.lang': 'Langue',
    'gen.captions': 'Sous-titres',
    'gen.seo': 'SEO Master (Google/YT)',
    'gen.voice': 'Voix de Narration',
    'gen.submit': 'Lancer le Rendu',
    'gen.loading': 'Génération du chef-d\'œuvre...',
    'gen.audio.title': 'Audio et Atmosphère',
    'gen.audio.music': 'Bande Originale (IA)',
    'gen.audio.sfx': 'Effets Sonores (SFX)',
    'gen.image.title': 'Studio Image',
    'gen.image.subtitle': 'Transformez du texte en art visuel 4K ultra-réaliste.',
    'gen.thumb.title': 'Créateur de Miniatures ⚡',
    'gen.thumb.subtitle': 'Créez des couvertures virales pour YouTube avec l\'IA.',
    'gen.thumb.bg': 'Scène / Arrière-plan',
    'gen.thumb.text1': 'Texte Principal',
    'gen.thumb.text2': 'Texte Secondaire',
    'history.title': 'Bibliothèque de Créations',
    'history.subtitle': 'Gérez, visualisez et téléchargez vos assets.',
    'history.retention': 'Fichiers conservés pendant 90 jours.',
    'history.empty': 'Aucun contenu généré pour le moment.',
    'pricing.title': 'Plans et Tarifs',
    'pricing.subtitle': 'Choisissez le niveau de puissance de calcul nécessaire.',
    'pricing.start': 'Commencer',
    'pricing.current': 'Votre Plan Actuel',
    'login.title': 'Accédez au futur',
    'login.subtitle': 'Accédez au futur de la création de contenu.',
    'login.email': 'Email',
    'login.pass': 'Mot de passe',
    'login.name': 'Nom',
    'login.submit_in': 'Entrer sur la Plateforme',
    'login.submit_up': 'Créer un Compte Gratuit',
    'login.toggle_in': 'Déjà un compte ? Connexion',
    'login.toggle_up': 'Pas de compte ? Créer',
    'error.credits': 'Crédits insuffisants.',
    'error.prompt': 'Veuillez décrire le contenu.',
    // Profile
    'profile.title': 'Paramètres de Profil',
    'profile.subtitle': 'Gérez vos informations personnelles et votre apparence.',
    'profile.name': 'Nom d\'affichage',
    'profile.email': 'Email (Lecture seule)',
    'profile.avatar': 'URL de l\'Avatar',
    'profile.save': 'Enregistrer',
    'profile.saving': 'Enregistrement...',
    'profile.success': 'Profil mis à jour avec succès !',
  },
  de: {
    'nav.dashboard': 'Dashboard',
    'nav.video': 'Video erstellen',
    'nav.image': 'Bild erstellen',
    'nav.thumbnail': 'Thumbnail erstellen',
    'nav.gallery': 'KI-Galerie',
    'nav.history': 'Verlauf',
    'nav.plans': 'Preise',
    'nav.admin': 'Admin-Panel',
    'nav.logout': 'Abmelden',
    'credits.remaining': 'Verbleibende Credits',
    'credits.upgrade': 'Upgrade',
    'credits.unlimited': 'unbegrenzt',
    'dashboard.hello': 'Hallo',
    'dashboard.subtitle': 'Dein KI-gestütztes Studio für Content-Erstellung.',
    'dashboard.new_project': '+ Neues Projekt',
    'dashboard.credits': 'Credits',
    'dashboard.renews': 'Erneuert in 30 Tagen',
    'dashboard.plan': 'Aktueller Plan',
    'dashboard.upgrade_link': 'Jetzt upgraden',
    'dashboard.status': 'Netzwerkstatus',
    'dashboard.start': 'Erstellung starten',
    'card.video.title': 'Video Studio',
    'card.video.desc': 'Erstelle Langform-Videos mit Narration.',
    'card.image.title': 'Image Lab',
    'card.image.desc': 'Erstelle visuelle Assets und 4K-Kunst.',
    'card.thumb.title': 'Thumbnail Maker',
    'card.thumb.desc': 'Virale Cover mit optimierter Typografie.',
    'common.loading': 'Laden...',
    'theme.title': 'Thema',
    'theme.cosmic': 'Cosmic (Standard)',
    'theme.aurora': 'Aurora (Tech)',
    'theme.inferno': 'Inferno (Kreativ)',
    // New Generative Pages
    'gen.video.title': 'Neues KI-Video',
    'gen.video.subtitle': 'Wähle KI-Modell, Stimme und generiere kinoreife Videos.',
    'gen.model': 'Künstliche Intelligenz Engine',
    'gen.prompt': 'Beschreibung (Prompt)',
    'gen.duration': 'Dauer',
    'gen.aspect': 'Seitenverhältnis',
    'gen.style': 'Visueller Stil',
    'gen.lang': 'Sprache',
    'gen.captions': 'Untertitel',
    'gen.seo': 'SEO Master (Google/YT)',
    'gen.voice': 'Erzählerstimme',
    'gen.submit': 'Rendering starten',
    'gen.loading': 'Generiere Meisterwerk...',
    'gen.audio.title': 'Audio & Atmosphäre',
    'gen.audio.music': 'Soundtrack (KI)',
    'gen.audio.sfx': 'Soundeffekte (SFX)',
    'gen.image.title': 'Bild Studio',
    'gen.image.subtitle': 'Verwandle Text in ultra-realistische 4K-Kunst.',
    'gen.thumb.title': 'Thumbnail Maker ⚡',
    'gen.thumb.subtitle': 'Erstelle virale YouTube-Cover mit KI.',
    'gen.thumb.bg': 'Szenario / Hintergrund',
    'gen.thumb.text1': 'Haupttext',
    'gen.thumb.text2': 'Sekundärtext',
    'history.title': 'Kreations-Bibliothek',
    'history.subtitle': 'Verwalte und lade deine generierten Assets herunter.',
    'history.retention': 'Dateien werden 90 Tage lang gespeichert.',
    'history.empty': 'Noch keine Inhalte generiert.',
    'pricing.title': 'Pläne & Preise',
    'pricing.subtitle': 'Wähle das benötigte Rechenleistungs-Level.',
    'pricing.start': 'Jetzt starten',
    'pricing.current': 'Dein aktueller Plan',
    'login.title': 'Zugang zur Zukunft',
    'login.subtitle': 'Zugang zur Zukunft der Content-Erstellung.',
    'login.email': 'E-Mail',
    'login.pass': 'Passwort',
    'login.name': 'Name',
    'login.submit_in': 'Plattform betreten',
    'login.submit_up': 'Kostenloses Konto erstellen',
    'login.toggle_in': 'Konto vorhanden? Anmelden',
    'login.toggle_up': 'Kein Konto? Erstellen',
    'error.credits': 'Unzureichende Credits.',
    'error.prompt': 'Bitte beschreibe den Inhalt.',
    // Profile
    'profile.title': 'Profileinstellungen',
    'profile.subtitle': 'Verwalte deine persönlichen Informationen.',
    'profile.name': 'Anzeigename',
    'profile.email': 'E-Mail (Schreibgeschützt)',
    'profile.avatar': 'Avatar URL',
    'profile.save': 'Änderungen speichern',
    'profile.saving': 'Speichern...',
    'profile.success': 'Profil erfolgreich aktualisiert!',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt');

  const t = (key: string): string => {
    if (translations[language][key as keyof typeof translations['pt']]) {
        return translations[language][key as keyof typeof translations['pt']];
    }
    
    if (translations['pt'][key as keyof typeof translations['pt']]) {
        return translations['pt'][key as keyof typeof translations['pt']];
    }

    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
